backend:
  name: git-gateway
  branch: master

media_folder: "/images/"
public_folder: "/"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        media_library:
          config:
            multiple: true
      - { label: "Body", name: "body", widget: "markdown" }
